#ifndef PROJECT_INCLUDE_RET_CODES_H_
#define PROJECT_INCLUDE_RET_CODES_H_

enum ret_codes {
    ERR_GET_BLACKRECORD_DATA = -6,
    ERR_GET_TRANSACTION_DATA,
    ERR_GET_RECORD_DATA,
    ERR_PRINT_FILE,
    ERR_TEST_RESULTS,
    ERR_MY_TEST,
    OK
};

#endif  // PROJECT_INCLUDE_RET_CODES_H_
